import Head from 'next/head'
import HeroSection from './landingPage/HeroSection'
import Skills from './landingPage/Skills'
import AboutMe from './landingPage/AboutMe'
import Contact from './landingPage/Contact'
import Footer from './landingPage/Footer'



export default function Home() {
  return (
    <>
      <Head>
        <title>Behcet Ozer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <Skills />
        <AboutMe />
        <div className="w-full flex whitespace-nowrap justify-center">
          <div className="flex justify-center w-[10%] border-b-2 border-[#83FFD2] text-[32px] font-bold mb-[5rem]">
            <h1>Contact Me</h1>
          </div>
        </div>
        <Contact />
        <Footer />
      </main>
    </>
  )
}
